


#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=secret


server:
    port: 9000

logging:
    level:
        org.springframework.security: trace



spring:
    datasource:
      url: jdbc:postgresql://localhost:5431/mydatabase
      username: myuser
      password: secret
    sql:
        init:
            mode: always
    application:
        name: demo-cloud-gateway-auth
    security:
        user:
            name: user1
            password: 1
        oauth2:
            authorizationserver:
                client:
                    messaging-client:
                        registration:
                            client-id: "messaging-client"
                            client-secret: "{noop}secret"
                            client-authentication-methods:
                                - "client_secret_basic"
                            authorization-grant-types:
                                - "authorization_code"
                                - "refresh_token"
                                - "client_credentials"
                            redirect-uris:
                                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                                - "http://127.0.0.1:8080/authorized"
                            post-logout-redirect-uris:
                                - "http://127.0.0.1:8080/logged-out"
                            scopes:
                                - "openid"
                                - "profile"
                                - "message.read"
                                - "message.write"
                        require-authorization-consent: true